const $=s=>document.querySelector(s);const bank=window.QUESTION_BANK;let set=[],i=0,answered=false,used={fifty:false,book:false,audience:false},score=0,questionTimer=null;
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
function optionQuality(q){
  const lengths=q.a.map(x=>x.length),max=Math.max(...lengths),min=Math.min(...lengths);
  const giveaway=/^(chỉ|hoàn toàn|không bao giờ|mọi|duy nhất)\b/i;
  const obvious=q.a.slice(1).filter(x=>giveaway.test(x)).length;
  return 100-(max-min)-obvious*18;
}
function takeTier(level,count){
  return shuffle(bank.filter(x=>x.d===level).sort((a,b)=>optionQuality(b)-optionQuality(a)).slice(0,Math.max(count,20))).slice(0,count);
}
function buildSet(){return [...takeTier(1,2),...takeTier(2,7),...takeTier(3,6)]}
const prizes=[200000,400000,600000,1000000,2000000,3000000,6000000,10000000,14000000,22000000,30000000,40000000,60000000,85000000,150000000];
const money=n=>n.toLocaleString("vi-VN")+" ₫";
function ladder(){$("#ladder").innerHTML=[...prizes].reverse().map((n,x)=>`<div class="rung ${(x===0||x===5||x===10)?'safe':''}" data-n="${15-x}"><b>${15-x}</b><span>${money(n)}</span></div>`).join("")}
function startTimer(){clearInterval(questionTimer);let left=150;$(".timer").classList.remove("idle","danger");$("#timerText").textContent="15";$("#timerBar").style.width="100%";questionTimer=setInterval(()=>{left--;const seconds=Math.ceil(left/10);$("#timerText").textContent=seconds;$("#timerBar").style.width=(left/1.5)+"%";$(".timer").classList.toggle("danger",left<=50);if(left<=0){clearInterval(questionTimer);answered=true;document.querySelectorAll(".answer").forEach(b=>b.disabled=true);$("#feedback").innerHTML="<p><strong>HẾT GIỜ.</strong> Cuộc chơi dừng tại câu này.</p>";setTimeout(()=>finish(false),900)}},100)}
function show(){answered=false;$("#next").classList.add("hidden");const q=set[i],letters="ABCD",order=shuffle(q.a.map((text,idx)=>({text,ok:idx===q.k})));$("#levelLabel").textContent=`CÂU ${i+1} / 15`;$("#chapter").textContent="KINH TẾ CHÍNH TRỊ MLN131";$("#difficulty").textContent=["","KHỞI ĐỘNG","PHÂN BIỆT","CHUYÊN SÂU"][q.d];$("#question").textContent=q.q;$("#feedback").innerHTML="";$("#answers").innerHTML=order.map((o,n)=>`<button class="answer" data-ok="${o.ok}"><b>${letters[n]}:</b>${o.text}</button>`).join("");document.querySelectorAll(".answer").forEach(b=>b.onclick=()=>answer(b,q));document.querySelectorAll(".rung").forEach(r=>{r.classList.toggle("active",+r.dataset.n===i+1);r.classList.toggle("done",+r.dataset.n<i+1)});startTimer()}
function answer(btn,q){if(answered)return;answered=true;clearInterval(questionTimer);document.querySelectorAll(".answer").forEach(b=>{b.disabled=true;if(b.dataset.ok==="true")b.classList.add("correct")});if(btn.dataset.ok==="true"){score++;$("#feedback").innerHTML=`<p><strong>CHÍNH XÁC.</strong> ${q.e}<br>Trang tham chiếu cần kiểm chứng: Chương ${q.c}, trang ${q.p}.</p>`;$("#next").textContent=i===14?"XEM KẾT QUẢ":"CÂU TIẾP THEO";$("#next").classList.remove("hidden")}else{btn.classList.add("wrong");$("#feedback").innerHTML=`<p><strong>CHƯA CHÍNH XÁC.</strong> ${q.e}<br>Trang tham chiếu cần kiểm chứng: Chương ${q.c}, trang ${q.p}.</p>`;setTimeout(()=>finish(false),1700)}}
function finish(win){clearInterval(questionTimer);const reached=win?15:i;const guaranteed=reached>=10?prizes[9]:reached>=5?prizes[4]:0;const reward=win?prizes[14]:guaranteed;openModal(win?"CHINH PHỤC CÂU 15":"CUỘC CHƠI KẾT THÚC",`<p>Bạn đã trả lời đúng <b>${score}/${i+1}</b> câu.</p><p>Tiền thưởng nhận được:</p><h3>${money(reward)}</h3><button class="primary" onclick="location.reload()">CHƠI LẠI</button><button class="primary" style="margin-left:8px" onclick="location.href='../../games.html'">VỀ TRANG GAME</button>`)}
function openModal(t,b){$("#modalTitle").textContent=t;$("#modalBody").innerHTML=b;$("#modal").showModal()}
$("#start").onclick=()=>{set=buildSet();i=score=0;$("#start").classList.add("hidden");show()};$("#next").onclick=()=>{if(i===14)return finish(true);i++;show()};
$("#fifty").onclick=e=>{if(answered)return;used.fifty=true;e.currentTarget.classList.add("used");const wrong=shuffle([...document.querySelectorAll('.answer')].filter(b=>b.dataset.ok==='false')).slice(0,2);wrong.forEach(b=>b.style.visibility='hidden')};
$("#book").onclick=e=>{if(answered||!set.length)return;used.book=true;e.currentTarget.classList.add("used");const q=set[i];openModal("GỢI Ý TỪ NGÂN HÀNG CÂU HỎI",`<p>${q.e.replace(/^.*?\./,'Hãy chú ý khái niệm trung tâm của câu hỏi.')}</p><p><small>Chương ${q.c}, trang ${q.p}</small></p>`)};
$("#audience").onclick=e=>{if(answered)return;used.audience=true;e.currentTarget.classList.add("used");const bs=[...document.querySelectorAll('.answer')],correct=bs.findIndex(b=>b.dataset.ok==='true'),wrong=[0,1,2,3].filter(x=>x!==correct);const leader=Math.random()<.6?correct:wrong[Math.floor(Math.random()*wrong.length)];const leadValue=40+Math.floor(Math.random()*18),others=[0,1,2,3].filter(x=>x!==leader),weights=others.map(()=>5+Math.random()*20),weightTotal=weights.reduce((a,b)=>a+b,0),vals=[0,0,0,0];vals[leader]=leadValue;let assigned=leadValue;others.forEach((idx,n)=>{vals[idx]=n===others.length-1?100-assigned:Math.max(3,Math.round((100-leadValue)*weights[n]/weightTotal));assigned+=vals[idx]});openModal("Ý KIẾN HỘI TRƯỜNG",`<div class="poll">${vals.map((v,n)=>`<div class="bar"><i style="--h:${v*2}px"></i><b>${'ABCD'[n]} ${v}%</b></div>`).join('')}</div><p><small>Ý kiến hội trường chỉ mang tính tham khảo.</small></p>`)};
$("#modal .close").onclick=()=>$("#modal").close();ladder();
